### ISSUE TITLE
Documentation on "pulling" ENV changes

### ISSUE THREAD

**Issue by ctrlaltdylan** [envkey/envkey-source#11]
Hi, we're using envkey-source with our EBS powered environments.

I'm having a hard time finding out how to force our environments to pull the latest ENVkey changes and applying them.

I've tried restarting our instances but I'm not sure if there's a shell script or something similar to actually pull the latest changes and applying them locally. Some documentation explaining how to do this would be great.

Thanks!

**Comment by danenania** [comment]
Hi! It sounds like you may need the `--force` (or `-f`) flag to allow for overwriting existing environment variables. 

`eval $(envkey-source --force)` 

Without it, envkey-source will defer to existing variables in order to allow for environment-specific overrides, so repeat invocations won't have any effect, but with that flag, all environment variables will be overwritten with the latest values from EnvKey.

**Comment by danenania** [comment]
Closing this, but lmk if you have any questions on this @ctrlaltdylan
